#operators
x=15
y=10
#addition
print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Floor Division:", x // y)
print("Modulus:", x % y)
print("Exponentiation:", x ** y)
print("Comparison Operators:")
print("Equal to:", x == y)
print("Not equal to:", x != y)
print("Greater than:", x > y)
print("Less than:", x < y)
print("Greater than or equal to:", x >= y)
print("Less than or equal to:", x <= y)
print("Logical Operators:")
print("Logical AND:", x > 0 and y > 0)
print("Logical OR:", x > 0 or y < 0)    
print("Logical NOT:", not(x > 0))
print("Bitwise Operators:")
print("Bitwise AND:", x & y)
print("Bitwise OR:", x | y)
print("Bitwise XOR:", x ^ y)
print("Bitwise NOT:", ~x)
print("Bitwise Left Shift:", x << 1)
print("Bitwise Right Shift:", x >> 1)